
print ("")
lista = [1, 2, "c", 7, 3,'d' ]
print(lista)
print ("Wyświetlenie listy zawierającej 6 elementów")
print ("")
print(lista[5])
print ("Wyświetlenie tylko szóstego elementu tej listy")
print ("")
lista[2] = 3
print ("Zmiana trzeciego elementu tej listy z (c) na (3)")
print ("")
print(lista)
print ("Wyświetlenie zmienionej listy zawierającej 6 elementów")
print ("")
tekst = "Hello World"
print (tekst)
print ("Zmienna tekstowa (tekst) jest traktowana jak lista.")
print ("")
print (tekst [6])
print ("Wyświetlenie siódmego znaku listy tekst.")
print ("")
print(lista + ['f',12]) 
print("Dodanie drugiej listy, ale tylko do wyświetlenia.")
print ("")
print(lista)
print("Widać że lista nie została powiększona o 2 elementy.")
print ("")
print ("Ilość elementów w liście: ", len(lista))
print("Odczytanie ilości elementów w liście (lista), zawiera 6 elementów.")
print ("")
print ("Ilość elementów w liście: ", len(tekst)) 
print("Odczytanie ilości elementów w liście (tekst), zawiera 11 elementów.")
print ("")
print(lista * 3) 
print("Pomnorzenie listy (lista) razy 3, zawiera 18 elementów.")
print ("")
lista.append(["j","k"])
print("operator kropka (.) pozwala odwołać się do metody append.")
print("Dodanie 2 elementów na końcu listy (lista), tylko na koncu.")
print ("")
print(lista) 
print("Teraz lista jest powiększona o 2 elementy,lista w liście.")
print ("")
print (lista[6][1])
print("Wyświetlenie drugiego elementu w drugiej liście.")
print ("")
lista.insert(3,17)
print("Wstawia 17 na 4 pozycji pierwszej listy, a resztę przesuwa.")
print ("")
print(lista)
print("Wyświetla obie listy po zmianie.")
print ("")
print("Ilość 3: ", lista.count(3))# ile razy wystąpiła cyfra 3
print("Ilość 17: ", lista.count(17))# ile razy wystąpiła cyfra 3
print("Ilość d: ", lista.remove("d"))# ile razy wystąpiła cyfra 3
print("Ile razy wystąpił dany element, wyszukuje tylko w pierwszej liście")
print ("")
print (lista)
print("Wyświetla obie listy.")
print ("")
lista2 = [1, 20, 30, -35, 5, 0]
print ("Min: ", min(lista2))
print ("Max: ", max(lista2))
print("Wyszukiwanie najmniejszej i najwiekszej  wartości elementu z listy.")

print("")
lista2.sort()
print (lista2)
print("lista2, posortowana rosnąco.")
print("")
